# Generated by Django 6.0.1 on 2026-04-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('patient_satisfaction_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('referral_bonus_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat dollar amount offered as referral bonus, if any.', max_digits=10, null=True)),
                ('average_turnaround_hours', models.PositiveIntegerField(help_text='Average turnaround time in hours for typical studies.')),
                ('patients_previously_referred', models.PositiveIntegerField(default=0)),
                ('public_transit_score', models.PositiveIntegerField(blank=True, help_text='Optional public transit accessibility score (future scope).', null=True)),
                ('insurance_plans', models.ManyToManyField(blank=True, related_name='imaging_centers', to='insurance.insuranceplan')),
                ('modalities', models.ManyToManyField(blank=True, related_name='imaging_centers', to='radiology.modality')),
            ],
        ),
    ]
